# Generated by Django 4.2 on 2023-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.IntegerField(choices=[('1', 'LIKE'), ('-1', 'DISLIKE')], help_text='1=LIKE,-1=DISLIKE', null=True),
        ),
    ]
